### ISSUE TITLE
怪文件（

### ISSUE THREAD

**Issue by RaySky-Rt** [Charles-IX/Code-Exercise#1]
看起来Helloworld文件夹里有一个不可名状的没有拓展名的二进制文件，为什么会有这东西（
![image](https://github.com/Charles-IX/Code-Exercise/assets/66870364/625f925c-91a6-49a8-81ee-8e210156217c)
~~对了，代码练习大概没必要把exe文件传上来，只上传源代码就可以了（~~

**Comment by Charles-IX** [comment]
已修正。没有扩展名的二进制文件是Linux版VScode编译的产物。
我已经修改了配置，要求Linux端生成的可执行文件以.out为后缀名。
.gitignore文件也得到了修正，现在不再上传*.out和*.exe。
